### ISSUE TITLE
More or less intensive than a full VM?

### ISSUE THREAD

**Issue by dannyvoid** [sebgl/htpc-download-box#3]
First, I'd like to say thanks for organizing all of this! It will make my transition so much easier since I'd like to start using dockers when possible. But I was wondering if this kind of setup would be more or less resource heavy compared to just a single VM running all native versions of these programs.

**Comment by sebgl** [comment]
Is your VM running locally on the same server the containers would otherwise run on? In such case, I'd say it's more lightweight to run containers directly instead of the VM.
More generally, I tend to think containers are a nice and reproductible way to run these programs, which makes long-term maintenance easier.
